### ISSUE TITLE
Better FixUTF8 in LoadFile

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#556]
My problem: I have a lot of legacy code, which was written for LuaForWindows using the Windows-Codepage. When I open this with zbs, I see the messages

> /home/joergen/Lua/quote-example.lua:7: Replaced an invalid UTF8 character with .
> /home/joergen/Lua/quote-example.lua:8: Replaced an invalid UTF8 character with .
> /home/joergen/Lua/quote-example.lua:9: Replaced an invalid UTF8 character with .
> /home/joergen/Lua/quote-example.lua:10: Replaced an invalid UTF8 character with .

and the code looks like this:
```lua
local known_escapes=
{
['<']="&lt;",
['>']="&gt;",
['&']="&amp;",
['\n']="<br>",
['"']="&quot;",
['']="&Auml;",
['']="&Ouml;",
['']="&Uuml;",
['']="&auml;",
['']="&ouml;",
['']="&uuml;",
['']="&szlig;",
}
```

It's OK for zbs to mark a problem with the code not being UTF8, but with the current implementation the important information (character codes) is LOST and cannot be repaired or even reviewed from within zbs.

In zbs debugger there is the code
```lua
local function fixUTF8(...)
  local t = {...}
  -- convert to escaped decimal code as these can only appear in strings
  local function fix(s) return '\\'..string.byte(s) end
  for i = 1, #t do t[i] = FixUTF8(t[i], fix) end
  return unpack(t)
end
```
Placing this into commands.lua
```diff
- s, invalid = FixUTF8(s, replacement)
+ s, invalid = FixUTF8(s, function (s) return '\\'..string.byte(s) end)
```
Gives on load of the example
```lua
local known_escapes=
{
['<']="&lt;",
['>']="&gt;",
['&']="&amp;",
['\n']="<br>",
['"']="&quot;",
['\196']="&Auml;",
['\214']="&Ouml;",
['\220']="&Uuml;",
['\228']="&auml;",
['\246']="&ouml;",
['\252']="&uuml;",
['\223']="&szlig;",
}
```
which is *much* better. Now, if you want to be able to detect the changed places, you can finally use
```diff
- s, invalid = FixUTF8(s, replacement)
+ s, invalid = FixUTF8(s, function (s) return replacement..'\\'..string.byte(s) end)
```
which will result in
```lua
local known_escapes=
{
['<']="&lt;",
['>']="&gt;",
['&']="&amp;",
['\n']="<br>",
['"']="&quot;",
['\196']="&Auml;",
['\214']="&Ouml;",
['\220']="&Uuml;",
['\228']="&auml;",
['\246']="&ouml;",
['\252']="&uuml;",
['\223']="&szlig;",
}
```
This gives us the best of both worlds
* Modified places are marked with SYN, so you can search for this ¹)
* No information loss, codes are replaced by escapes, which can be then used to create correct code.

--
¹) Can you? How do I easily search for SYN, how can I enter this in the find text entry?

**Comment by pkulchenko** [comment]
This is a tricky one; I'm hesitant to make the changes here as I expect #260 to fix this issue (as it adds `*Raw` calls that allow to read/write "invalid" UTF-8 characters without modifications (they would be displayed as `[hexcode]` by the editor). There was also a discussion on converting non UTF-8 encodings when reading a file and then converting it back (#543). I'm working on the wxwidgets upgrade (as documented in #260) and expect to have a modified version soon that should be able to correctly handle those files in the editor.

**Comment by jjvbsag** [comment]
Ok, I'll wait for your results. If I understand it correct, the files won't be modified any more. Great.

But then still there are "none-utf8" chars in the legacy code. These should be fixed anyway. Maybe you can think over a package (or built-in function) which add a "convert none ascii-characters in selection to \nnn notation" to the editor.

Thanks, Regards

**Comment by pkulchenko** [comment]
The idea is to keep the characters preserved exactly as is. The current issue is that all `GetText` and `SetText` calls pass only UTF-8 valid code, but all `*TextRaw` methods keep it as byte stream and allow Scintilla to deal with them.

Those non-utf8 chars don't need to be "fixed" in this case; you'll see them similar to how Scintilla displays control characters. Although it wouldn't hurt to have a package that does the conversion (as discussed in #543).

**Comment by jjvbsag** [comment]
I disagree in one point: #543 will change the semantic of the lua-code (written with \nnn for clarity).
Before iconv: `['\196']="&Auml;",`
After iconv: `['\195\132']="&Auml;",`
Thats different code which will render the function invalid

**Comment by pkulchenko** [comment]
@jjvbsag, it depends on what the user want; it may be useful to have both options: (1) using `*Raw` methods will allow the user to keep `\196` if they want to preserve the original encoding, (2) using conversion the user may convert the code into UTF-8 (if desired), but may also convert into original encoding when saving the file.

The difference between the two options is that in the first case the editor keeps the code as bytestream and displays UTF-8 invalid characters as `[hex]`, but in the second case everything is kept and shown as valid UTF-8 (assuming it's been correctly converted into UTF-8).

**Comment by jjvbsag** [comment]
I'd prefer to use the first option (`Raw`) by default. And then give the possibility to either convert to \nnn or to convert to utf8 via iconv as needed by the user via an edit command.

Looking forward to your next build :smiley:

Regards Jørgen

**Comment by pkulchenko** [comment]
Right; that's exactly the idea. I plan to modify the existing code to provide a hybrid function that will dynamically identify what `Raw` functions are available, which will allow to use/test the updated code with different version of wxwidgets/wxlua. I already have the Window builds done, just need to update all the calls to use the new functions. I'll update the ticket when I have that available.

**Comment by pkulchenko** [comment]
@jjvbsag, I pushed the changes to a temporary branch (https://github.com/pkulchenko/ZeroBraneStudio/tree/wxstc-raw). It includes required changes to add the `*Raw` methods and to upgrade the wxlua/wxwidgets library on Windows. The changes to the `*Raw` methods will be migrated to the master branch, but the binary upgrade will be redone later to use the same version for all supported platforms.

You can see the effect of the changes if you run this script and save the results in a file (or just open a file with invalid UTF-8 characters):

```lua
print("--\193 \205 \207 \208 \221--")
```

You should see those characters as special hex symbols, but you should still be able to edit and save the file without those characters present. Let me know if you notice any issues with the search or Output/Console panels.

There are still some improvements to be done, as the Output/Console panels still displays `SYN` instead of the actual hex code as it's done in the editor, but this may require some more work.

**Comment by pkulchenko** [comment]
@jjvbsag, pushed one more change that updates Output/Console text, so that it displays invalid characters the same way as they are shown in the editor. I think these are the all changes we need for this ticket. Let me know how it works for your files and I'll merge this into master (minus the binary).

**Comment by jjvbsag** [comment]
I checked out the branch on linux: No success, still using SYN
I checked out the branch on windows: Display works as expected. 
But then I tried to Copy'n'Paste within zbs a peace of code with 
`['xDC']="&Uuml;",`  ¹)
and the result was 
`['ܧ]="&Uuml;",` ²)
so there is more work to do.

FYI: Copying legacy-ISO code from Notepad and Pasting into zbs resulted in converting to UTF8. But this I would not count as a bug.

Regards Jørgen

¹) xDC is displayed as inverted hex code
²) Seems to be a code with RTL-Reading. Looking at it with SciTE gives strange cursor movements

**Comment by pkulchenko** [comment]
@jjvbsag, there wouldn't be any change on Linux as I only included Windows binary and both code and binary changes are required for every platform (so at this moment we can only test on Windows).

Good point on copy-n-paste. This is probably deep in Scintilla/wxwidgets and I'm not even sure if there is a good solution to this as the buffer is expected to be UTF8-valid and you are copying the invalid content. How does it look when you copy the same code from Notepad and Pasting into ZBS? What code does it generate as the result?

**Comment by jjvbsag** [comment]
I have done some research on windows. My teststring is a 6 character string containing 3 ascii chars and 3 german umlauts. (Hex codes in windows codepage is `616F75849481`)

#### This is put into the clipboard when copying with **SciTE** (in codepage mode)
```
fmt=13 (CF_UNICODETEXT)
>txt[14]="a\000o\000u\000\228\000\246\000\252\000\000\000"
>hex[14]=61006F007500E400F600FC000000
fmt=16 (CF_LOCALE)
>txt[4]="\007\004\000\000"
>hex[4]=07040000
fmt=1 (CF_TEXT)
>txt[7]="aou\228\246\252\000"
>hex[7]=616F75E4F6FC00
fmt=7 (CF_OEMTEXT)
>txt[7]="aou\132\148\129\000"
>hex[7]=616F7584948100
```
The same is when copied from Notepad
#### This is put into the clipboard when copying with **zbs** (wxstc-raw)
```
fmt=49161 (???)
>txt[4]="B\012\002\000"
>hex[4]=420C0200
fmt=13 (CF_UNICODETEXT)
>txt[10]="a\000o\000u\000\252]\000\000"
>hex[10]=61006F007500FC5D0000
fmt=49171 (???)
>txt[120]="\000\000\000\000x\000\000\000\001\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\r\000\000\000\000\000\000\000\001\000\000\000\255\255\255\255\001\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
>hex[120]=0000000078000000010000000100000000000000000000000D0000000000000001000000FFFFFFFF010000000100000000000000000000000000000000000000...
fmt=16 (CF_LOCALE)
>txt[4]="\007\004\000\000"
>hex[4]=07040000
fmt=1 (CF_TEXT)
>txt[5]="aou?\000"
>hex[5]=616F753F00
fmt=7 (CF_OEMTEXT)
>txt[5]="aou?\000"
>hex[5]=616F753F00
```
I'm not sure, if this is a problem in zbs passing wrong parameters to wxClipboard or a problem inside wxClipboard itself.

I'll attach the lua script, I use to dump the windows-clipboard (renamed to .txt, because you cannot attach .lua in github). You'll need LuaForWindows (or you need to add alien to zbs)  :smiling_imp:

[dump-windows-clipboard.txt](https://github.com/pkulchenko/ZeroBraneStudio/files/38723/dump-windows-clipboard.txt)

**Comment by pkulchenko** [comment]
Thank you for the script and for the information; this is going to be quite handy.

> This is put into the clipboard when copying with SciTE (in codepage mode)

What is "codepage mode"? The IDE has `editor:GetCodePage()` set to `wxstc.wxSTC_CP_UTF8` (65001). Is it the same for SciTE?

> I'm not sure, if this is a problem in zbs passing wrong parameters to wxClipboard or a problem inside wxClipboard itself.

This is not something that ZBS can control; in fact, I just call editor:Copy() method that Scintilla provides, but internally Scintilla calls CopyToClipboard method that wxwidgets implements, so the issue is likely to be there somewhere. I tried to copy to clipboard "manually" and I see some issues there too (although I didn't realize I can enumerate all the formats directly in the clipboard.

I posted a [question to the wxwidgets maillist](https://groups.google.com/d/msg/wx-dev/61a6yK7JYxw/utzdsLpnCAAJ). I'll update it with this information.

I *may* have a workaround for this issue, but it's an ugly one. Essentially, when Copying something, I'd need to check if it's a valid UTF-8 and if so, use the default Copy, but if not, use the "manual" process that sets `CF_TEXT` correctly. When Pasting, check the clipboard content for being a valid UTF-8 and if so, use the default Paste, but if not, use the "manual" process that gets byte content and does `InsertTextRaw`. I haven't fully implemented it yet, but preliminary tests shown that it may work. Still, I'd prefer not to do it this way.

**Comment by jjvbsag** [comment]
> What is "codepage mode"? 

In SciTE on the File-Menu there is a menu "Encoding", where you select which interpretation to use on the files opened. The choices are

* `Code page property`
* `UTF-16 Big Endian`
* `UTF-16 Little Endian`
* `UTF-8 with BOM`
* `UTF-8`

For `page property` you can define a config value `code.page` in `SciTEUser.properties`. This can be set to `65001` to startup in UTF-8 but also to e.g. `932` for Shift-JIS or simply to `0` (default) for a single byte character set.

**Comment by jjvbsag** [comment]
> I haven't fully implemented it yet, but preliminary tests shown that it may work. Still, I'd prefer not to do it this way.

I would not insist on copy'n'paste from/to other editors to/from zbs in this special situation, so don't spend to much time with it (although it would be nice if it works). 

But *surely* I'd expect copy'n'paste to work flawlessly *inside* zbs.

**Comment by pkulchenko** [comment]
@jjvbsag, can you set it to UTF-8/65001 (as it's set in the IDE) and see what the results are?

> But surely I'd expect copy'n'paste to work flawlessly inside zbs.

Fully agree; I'm working on a patch to test right now...

**Comment by jjvbsag** [comment]
Ok, next test (and then I go to bed ;-)

* Select `Code page property`
* enter `äöü`
* Switch to `UTF8`   ¹)
* Scite now displays xE4 xF6 xFC in inverted boxes
* select these 3 characters and [Ctrl]+[C]
* [Ctrl]+[V] 
* Scite past's arbitrary chinese characters `巼` so this looks like the same issue


¹) this is the same as setting code.page to 65001

**Comment by pkulchenko** [comment]
Yes, this looks like the same issue. Ok, I'll play with my patch and will check it in when I get it working. You'll have a change to try it when you wake up ;).

**Comment by pkulchenko** [comment]
@jjvbsag, I added a workaround that fixes the copying inside the IDE for me (I tried various combinations). I also fixed copying between the editor and the console, which wasn't working with `Shift-Ins`. I still need to test if the patch is needed on Linux and OSX.

**Comment by jjvbsag** [comment]
@pkulchenko I will not be in the office today, so I can verify on Monday earliest. sorry.

**Comment by pkulchenko** [comment]
No problem; I'm likely to have couple of improvements by that time. I'll probably merge these changes into master (as they should be working with the current version as well), but the binary for the new version will be still in the same branch. Thank you for your help.

**Comment by jjvbsag** [comment]
Test Results (wxstc-raw branch):
zbs for Window on windows : Copy'n'Past works as expected:
zbs for Windows on Linux-with-wine : Copy'n'Past works as expected:
zbs for Linux on Linux : still failing (as expected)

**Comment by pkulchenko** [comment]
Ok; thank you for testing. I'll merge the branch into the master shortly (without the binary).

I also tested on OSX and it works there as expected.

**Comment by pkulchenko** [comment]
@jjvbsag, I merged all the changes from `wxstc-raw` branch. I'll have the binaries updated for wxwidgets upgrade available in another branch shortly, but all this code should work with the current master branch (you just won't see any changes for the `[SYN]` handling there).

**Comment by pkulchenko** [comment]
Closed by the completion of #260 (merged wxwidgets31x-upgrade branch).
